### ISSUE TITLE
Diagonal matrix constructor issue

### ISSUE THREAD

**Issue by pierre-vigier** [pierre-vigier/Perl6-Math-Matrix#6]
For diagonal matric, the doc states:
my $matrix = Math::Matrix.diagonal( 2, 4, 5 );

however it does not work, as it's expected an array:
```perl6
method diagonal(Math::Matrix:U: @diag ){
```

Two solutions here, either fix the doc, or make the array greedy in prototype:
```perl6
method diagonal(Math::Matrix:U: *@diag ){
```

**Comment by lichtkind** [comment]
I fix that right now

**Comment by lichtkind** [comment]
allright fix is ready.
due to diag (1,2,3): yes its the simpler syntax and i already tried to use slurpy parameter. however I see there a bigger problem we maby solve better now which also includes the named parameter thing. Which im still fully positive about but the more i think the more i like an even better solution that is more powerful and changes less on situation now. I want to overload new so you can have multiple optional parameter, like default value, diagonal certain column and so on so you can define things like frobenius marices with at least syntax as possible but still in a clean understandable way. and the diag or zero are just special methods thet sit on top with often used defaults. like zero matrix just defines size and a default value. and i want to have a method to create matrix by vector product.

this has also so advantage so we can store values like determinant, and density right away because det zero = 0 also rank zero = 0 without calculating anything later.. to me its part of a larger plan which takes some thought and i have now other stuff to do but in case you like that we could indeed settle to diag (..,..,..) syntax instead of square brackets.

Thanks

**Comment by lichtkind** [comment]
is fixed now?

**Comment by pierre-vigier** [comment]
Sorry, yes it is, i merged it, and there's test cases for it
